default_install_hook_types: [pre-commit, commit-msg]
exclude: (/migrations/|manage.py|.svg|.drawio)
repos:
  - repo: https://github.com/base-angewandte/pre-commit-hooks
    rev: "2.1"
    hooks:
      - id: base-hooks
      - id: base-commit-msg-hooks
  - repo: https://github.com/adamchainz/django-upgrade
    rev: 1.15.0
    hooks:
      - id: django-upgrade
        args: [--target-version, "4.2"]
