# Generated by Django 4.2.20 on 2025-04-01 13:39

import base_common.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('slides', models.JSONField(default=list, verbose_name='Slides')),
                ('last_changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_album_changes', to=settings.AUTH_USER_MODEL, verbose_name='Last changed by')),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', base_common.fields.ShortUUIDField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
            ],
        ),
        migrations.CreateModel(
            name='PermissionsRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permissions', models.CharField(choices=[('VIEW', 'VIEW'), ('EDIT', 'EDIT')], default='VIEW', max_length=20)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album', to='artworks.album')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FolderAlbumRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_to_album', to='artworks.album')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_to_folder', to='artworks.folder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_to_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='folder',
            name='albums',
            field=models.ManyToManyField(related_name='folder_to_albums', through='artworks.FolderAlbumRelation', to='artworks.album', verbose_name='Albums'),
        ),
        migrations.AddField(
            model_name='folder',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folder_owner', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='folder',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folder_to_parent', to='artworks.folder'),
        ),
        migrations.AddField(
            model_name='album',
            name='permissions',
            field=models.ManyToManyField(related_name='permissions', through='artworks.PermissionsRelation', to=settings.AUTH_USER_MODEL, verbose_name='Permissions'),
        ),
        migrations.AddField(
            model_name='album',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
