# Generated by Django 4.2.20 on 2025-04-01 19:47

import shortuuid

import base_common.fields
from django.db import migrations


def regenerate_album_ids(apps, schema_editor):
    Album = apps.get_model('artworks', 'Album')
    for album in Album.objects.all():
        album.id = shortuuid.uuid()
        album.save()


def regenerate_album_ids_reverse(apps, schema_editor):
    Album = apps.get_model('artworks', 'Album')
    i = 1
    for album in Album.objects.all():
        album.id = str(i)
        album.save()
        i += 1


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='id',
            field=base_common.fields.ShortUUIDField(primary_key=True, serialize=False),
        ),
        migrations.RunPython(regenerate_album_ids, reverse_code=regenerate_album_ids_reverse),
    ]
