# Generated by Django 4.2.20 on 2025-04-01 19:28

import base_common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='id',
            field=base_common.fields.ShortUUIDField(primary_key=True, serialize=False),
        ),
    ]
